In [16]:
## Imports :

import numpy as np
import tensorflow as tf
import numpy.random as npr
import pandas as pd
import utils

## Session/Tensors examples :

In [2]:
## First session/tensors:

a = tf.add(3, 5)
print(a)
print('\n')
## return the tensor a not the value ! 
## To se the value need to create a session :
sess = tf.Session()
print(sess.run(a))
sess.close()

Tensor("Add:0", shape=(), dtype=int32)


8


In [3]:
## different way to create a session :
with tf.Session() as sess :
    print(sess.run(a))

8


In [4]:
## Graph :
x = 13
y = 1

add_op = tf.add(2*x, y)
mul_op = tf.multiply(x, y)
useless = tf.multiply(mul_op, add_op)
pow_op = tf.pow(add_op, mul_op)

with tf.Session() as sess:
    z, not_useless = sess.run([pow_op, useless])

print('frist_op : ', z)
print('second_op : ', not_useless)

'''
  Note :
  
  if for example we on ly want the value of pow_op, 
  to compute this value we don't need to compute the value of useless
  tensorflow will save the computation and ignore useless !
  
'''

frist_op :  -1201670133
second_op :  351


"\n  Note :\n  \n  if for example we on ly want the value of pow_op, \n  to compute this value we don't need to compute the value of useless\n  tensorflow will save the computation and ignore useless !\n  \n"

## Operations : Constant - Variables - Placeholders

In [5]:
## Tensorboard graph visualization with names...
a = tf.constant(2, name='a')
b = tf.constant(3, name='b')
x = tf.add(a, b, name='add')
# summary writer creation for tensorboard :
writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())
with tf.Session() as sess:
    print(sess.run(x))

writer.close()

5


In [6]:
## Constants :
'''
tf.constant(
            value,
            dtype=None,
            shape=None,
            name='Const',
            verify_shape=False
            )
'''

a = tf.constant([1,2])
b = tf.constant([[3,4],[1,9]])
x = tf.multiply(a,b)

with tf.Session() as sess:
    #matrix multplication with tensors
    print('matrix multiplication : \n', sess.run(x))
    # zeros matrix :
    print('zeros matrix : \n', sess.run(tf.zeros([3,4])))
    # lin space :
    print('lin space : \n', sess.run(tf.lin_space(5.0, 13.0, 4)))
    # range :
    print('range : \n', sess.run(tf.range(5)))
    print('range with diff: \n', sess.run(tf.range(5, 50, 10)))

matrix multiplication : 
 [[ 3  8]
 [ 1 18]]
zeros matrix : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
lin space : 
 [ 5.        7.666667 10.333334 13.      ]
range : 
 [0 1 2 3 4]
range with diff: 
 [ 5 15 25 35 45]


In [7]:
## Variables :
'''
Variable is a class with different operations while constant is only an operation !
get_Variable is better than Variable : allow to share data...
variables need initialization in order to compute -> done inside the session for all variables
'''

## First evaluation of a variable
var = tf.Variable(tf.constant([[2,5],[1,1]]))
with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    print('First evaluation of a variable : \n', var.eval())


First evaluation of a variable : 
 [[2 5]
 [1 1]]


In [8]:
'''
Define an operation that will be run multiple times 
need to precise it inside the session !
'''
    
## assign op
var = tf.Variable(10)
assign_op = var.assign(30)
with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    print('firt evaluation before running the op : \n', var.eval())
    ## run the assign op :
    sess.run(assign_op)
    print('second evaluation before running the op : \n', var.eval())

firt evaluation before running the op : 
 10
second evaluation before running the op : 
 30


In [9]:
var = tf.Variable(10)
assign_op = var.assign(2*var)
with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    print('firt evaluation before running the op : \n', var.eval())
    ## run the assign op :
    sess.run(assign_op)
    print('second assign before running the op : \n', var.eval())
    ## run the assign op :
    sess.run(assign_op)
    print('second assign before running the op : \n', var.eval())

firt evaluation before running the op : 
 10
second assign before running the op : 
 20
second assign before running the op : 
 40


In [10]:
var = tf.Variable(10)
with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    # add value :
    sess.run(var.assign_add(17))
    print(var.eval())
    # substruct value
    sess.run(var.assign_sub(13))
    print(var.eval())

27
14


In [11]:
'''
Placeholder give space to feed later : 
    like defining an input variable in python f(x,y) =.. 
    we give space to x and y to feed later
'''

a = tf.placeholder(tf.float32, shape=[3])
b = tf.constant([5,5,5], tf.float32)

def f(a):
    return a + b

with tf.Session() as sess :
    print( sess.run( f(a), feed_dict={a: [3, 2, 1]} ) )
    print('\n')

## run miultiple times with different values :
print('run miultiple times with different values : \n')
list_of_values = [[1, 1, 1], [4, 6, 1], [2, 2, 1], [8, 7, 1]]
with tf.Session() as sess :
    for value in list_of_values:
        print( sess.run( f(a), feed_dict={a: value} ) )


[8. 7. 6.]


run miultiple times with different values : 

[6. 6. 6.]
[ 9. 11.  6.]
[7. 7. 6.]
[13. 12.  6.]


In [12]:
## Feeding : useful for testing a part of a graph or certain operations
a = tf.add(2, 3)
b = tf.multiply(a, 2)
with tf.Session() as sess:
    # compute the value of b given a is 10
    print( sess.run(b, feed_dict={a: 10}) )   

20


## Get_variable :

The use of tf.get_variable is better than tf.variable :

    - Get_variable allow the model to reuse the same var (save space) and to save the model with this value
    
    !!! Name of the variable is very important and should be unique !!!
    
How to use it ex :

1. my_variable = tf.get_variable("my_variable", [1, 2, 3]) -> with [1,2,3] is the shape of the tensor
2. tf.get_variable("myy_variable", [1, 2, 3], initializer=tf.zeros_initializer) -> initialize at zero 
3. other_variable = tf.get_variable("other_variable", dtype=tf.int32, initializer=tf.constant([23, 42])) -> constant initialization



In [13]:
#var = tf.Variable(tf.constant([[2,5],[1,1]]))
var1 = tf.get_variable("my_new_var", [1], initializer=tf.zeros_initializer)
with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    #print('First evaluation of a variable : \n', var.eval())
    print('First evaluation of a variable : \n', var1.eval())

First evaluation of a variable : 
 [0.]


In [32]:
## let's consider the following function 

###__ First try 
def Hidden_layers(x):
    
    assert x.shape.as_list() == [200, 100]

    # If we use variable instead of get_varibale the model will initialize w and b at each call 
    w1 = tf.get_variable("h1_weights", [100, 50], initializer=tf.random_normal_initializer())
    b1 = tf.get_variable("h1_biases", [50], initializer=tf.constant_initializer(0.0))
    h1 = tf.matmul(x, w1) + b1

    assert h1.shape.as_list() == [200, 50]  

    w2 = tf.get_variable("h2_weights", [50, 10], initializer=tf.random_normal_initializer())
    b2 = tf.get_variable("h2_biases", [10], initializer=tf.constant_initializer(0.0))

    logits = tf.matmul(h1, w2) + b2
    return logits


with tf.variable_scope('two_layers') as scope:  #define the scope in order to reuse the variables :
    
    logits1 = Hidden_layers(x1)
    scope.reuse_variables()   #Allows to reuse the same weights for logits2 - otherwise error weights already used!
    logits2 = Hidden_layers(x2)


#******************************* best way to share variables (reuse the same model) ********************    
###__ In the previous we should write scope.reuse_variables() at each time we need to reuse them -> not efficient!
### we can specify resue when we creat the variables :

def FC(x, output_dim, scope):
    
    ##create variables within a scope and specify reuse :
    with tf.variable_scope(scope, reuse=tf.AUTO_REUSE) as scope:

        w = tf.get_variable("weights", [x.shape[1], output_dim], initializer=tf.random_normal_initializer())
        b = tf.get_variable("biases", [output_dim], initializer=tf.constant_initializer(0.0))
        return tf.matmul(x, w) + b

def two_hidden_layers(x):
    h1 = FC(x, 50, 'h1')
    h2 = FC(h1, 10, 'h2')

with tf.variable_scope('two_layers') as scope:
    logits1 = two_hidden_layers(x1)
    logits2 = two_hidden_layers(x2)
    
    

    

NameError: name 'x1' is not defined

## Deal with Dataset :


Performs quicker than Placeholder biut can be tricky to use if there is a lot of preprocessing

In [29]:
data_path = '/Users/benjelloun/Documents/General_code/Hands_On_Tensorflow/data/birth_life_2010.txt'

# Step 1: Get the data == read in data from the .txt file
data, n_samples = utils.read_birth_life_data(data_path)
print('number of samples : ', n_samples)
print('\n \n')
print('small view of data : \n', data[:3, :])

number of samples :  190

 

small view of data : 
 [[ 1.822   74.82825]
 [ 3.869   70.81949]
 [ 3.911   72.15066]]


In [30]:
## STORE DATA in tf.data.Dataset((features, labels)) :

dataset = tf.data.Dataset.from_tensor_slices((data[:,0], data[:,1]))

# METHODS :
print('Output type : ', dataset.output_types)
print('\n')
print('Output shape : ', dataset.output_shapes)
print('\n')
"""
tf.data.TextLineDataset(filenames)
tf.data.FixedLengthRecordDataset(filenames)
tf.data.TFRecordDataset(filenames)
"""

# OPERATIONS - ITERATOR :

"""
Iterates through the dataset exactly once. No need to initialization :
    - iterator = dataset.make_one_shot_iterator() 

Iterates through the dataset as many times as we want. Need to initialize with each epoch :
    - iterator = dataset.make_initializable_iterator()
"""
iterator = dataset.make_one_shot_iterator() 
X,Y = iterator.get_next() 

with tf.Session() as sess:
    print('Iterator data')
    print(sess.run([X, Y])) # >> [1.822, 74.82825]
    print(sess.run([X, Y])) # >> [3.869, 70.81949]
    print(sess.run([X, Y]))
    
## Methods :
#dataset = dataset.shuffle(1000)  ## shuffle the dataset
#dataset = dataset.repeat(100)
#dataset = dataset.batch(128) ##-> Convert the dataset into batches of size 128
#dataset = dataset.map(lambda x: tf.one_hot(x, 10))  #convert each elem of dataset to one_hot vector



Output type :  (tf.float32, tf.float32)


Output shape :  (TensorShape([]), TensorShape([]))


Iterator data
[1.822, 74.82825]
[3.869, 70.81949]
[3.911, 72.15066]


## Optimizers 

1.__ define the optimizer :
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001).minimize(loss)

2.__ run the optimizer into a Session :
_, l = sess.run([optimizer, loss], feed_dict={X: x, Y:y})

How it does work :
    Session looks at all trainable variables that loss depends on and update them (should specigy trianable=True is we want to train a variable!)

In [ ]:
## opt = tf.train.AdamOptimizer(learning_rate=0.01).minimize(loss)
## within the session _,loss_ = sess.run([opt, loss]..)

## Save-Restore models

    - Save line : tf.train.Saver.save(sess, save_path, global_step=None...)

    - restore line : tf.train.Saver.restore(sess, save_path)


Note : save will save the weights and not the graph, in adition it will save a checkpoint file which can map variables name to tensors. 

In [ ]:
##___________ Save a model after a certain number of iterations :



#call the model : for ex MyModel
model = MyModel(parameters)
# create a saver object
saver = tf.train.Saver()

with tf.Session() as sess:
    
    for step in range(training_steps):
        # optimizaiton step
        sess.run([optimizer])
        
        # save the model after n steps
        if step%n == 0:
            
            saver.save(sess, 'checkpoint_directory/model_name', global_step=step)

        
##___________ Load a model after a certain number of iterations :  



## Neural Networks functions :

In [ ]:
## 2.___ Convolution layer :
# perform a convolution

conv1 = tf.layers.conv2d(inputs=image,
                        filters = 32,
                        kernel_size = [5, 5],
                        padding='SAME',
                        activation=tf.nn.relu,
                        name='conv1')

# Pooling operation :
pool1 = tf.layers.max_pooling2d(inputs=input, 
                                pool_size=[2, 2], 
                                strides=2,
                                name='pool1')

# Dense layer :
fc = tf.layers.dense(input, 1024, activation=tf.nn.relu, name='fc')

# Dropout :
dropout = tf.layers.dropout(fc, self.keep_prob, training=self.training, name='dropout')

## TF-Records

    - Make better use of disk cache
    - Faster 